### ISSUE TITLE
Suggestions about the icon, the thumbnails and the displayed text

### ISSUE THREAD

**Issue by ArmorKeik** [ItzBlinkzy/roblox-rpc#1]
This is the most complete Rich Presence mod I've seen, but it's not perfect.

**1.** You have several games that are missing the thumbnail, such as: 🌴 Outlaster, Flee the Facility, Randomizer, etc.

![Captura de pantalla 2021-08-28 162633](https://user-images.githubusercontent.com/87909542/131231328-8f1e24b1-f577-418e-8f3e-b25adcb5c48b.png)

**2.** Since miniatures are needed it would be a good idea to add an option to change the Roblox logo (or even be able to customize it) that is shown when the game is missing the miniature (or to be able to choose to keep it forever).

![Roblox](https://user-images.githubusercontent.com/87909542/131231456-c883e880-e005-47db-87bb-2fe47658389a.jpg)
![Roblox_Player_icon](https://user-images.githubusercontent.com/87909542/131231461-5f2db371-7d66-4e67-ba6d-e507f3b7b03e.png)
![Robloxlogo2019](https://user-images.githubusercontent.com/87909542/131231463-cfe3e54b-26bd-4138-9e13-3ccff2938678.png)

**3.** The "Playing ..." could easily be replaced by a text showing the creator of the game. For example: "By: Peak Precision Studios" (author / group name should be below game name).

**4.** I recommend adding a file or an option in the application logo, in the task bar, to check for mod updates.

![Captura de pantalla 2021-08-28 183056](https://user-images.githubusercontent.com/87909542/131231510-e4bc6501-30f4-4516-9436-75dc5e1e37b9.png)

**5** Remove the "Game →" so that only the "ROBLOX" remains.

**Comment by ItzBlinkzy** [comment]
Thanks for giving these suggestions, I'll briefly talk about each suggestion.
## 1.
* Unfortunately due to how the internal system at Discord works, images are **cached** by their network, and we are limited to 300 images maximum, This means thumbnails cannot be changed at runtime so at the moment it is not possible to add a thumbnail for every ROBLOX game. 

* The only games that have thumbnails are the ones in the image below, let me know if there are any popular games you want with a thumbnail and I will add them.
![Limited images](https://user-images.githubusercontent.com/68260779/132571901-3d4c91cf-624e-443d-8bac-afddbb38f574.png)


## 2
* This suggestion also links back to the caching issue with Discord, however, I could add a small group of ROBLOX logos and allow the user to choose one before the program starts.

## 3
* The *"Playing..."* tag is pretty useless and as you suggested it would be beneficial to add some useful information there so I will be implementing this in the near future when I have free time.

## 4
* Yes, I've thought about it and I will also be implementing it because it won't be too hard to do.

## 5 
* Pretty simple change, I had that for personal use but I don't mind changing it to that so sure.

**Comment by ArmorKeik** [comment]
Hello, me again.

Well, I play Flee the Facility a lot (https://www.roblox.com/games/893973440/Flee-the-Facility).

To the Randomizer (https://www.roblox.com/games/5307215810/Randomizer-V-0-1-6-PART-ONE).

Al 🌴 Outlaster (https://www.roblox.com/games/5343994291/Outlaster).

And others, but if you want to add the most popular games; To make sure that the most played are as miniature, they can be found in this section (https://www.roblox.com/discover#/).

![Captura de pantalla (278)](https://user-images.githubusercontent.com/87909542/132914582-8b726199-fbfa-4e2f-87da-f326948ce93e.png)
![Captura de pantalla (279)](https://user-images.githubusercontent.com/87909542/132914591-aab04d71-5f60-4f5e-9952-5783c4f6f6d0.png)

**Comment by Bobrokus** [comment]
_You could add:_ **Retail Tycoon 2, grg., Defender's depot, Car Crushers 2, Survive and kill the killers in Area 51, Armored Patrol 9.5 and AP 2, 3008 [2.7] (Infinite IKEA), ZO, Loomian legacy, Wacky wizards, bulked up, Vans World, Super Doomspire, Build a boat for treasure, Booga Booga, Project lazarus, Horrific housing, Notoriety, Driving simulator, Pilot training flight simulator, Work at a pizza place, Cook burgers, Broken Bones and Friday Funkin'**.
